<<<<<<< HEAD
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['Hoxino.py'],  # 只保留主入口文件
    pathex=[],
    binaries=[],
    datas=[
        ('resources', 'resources'),  # 包含资源文件
    ],
    hiddenimports=[
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'queuemanagement',
        'queuemanagement.queuemanagement',
        'ui',
        'ui.Main_ui',
        'ui.setting_ui',
        'ui.tabmanager.tab_manager',
        'ui.PerformanceEvaluation.performance_evaluator',
        'ui.Miscellaneous.Backstage',
        'ui.menu.menu',
        'ui.menu.menu1',
        'ui.list.list',
        'Communications.url_receiver',
        'download.util.Settings_util',
        'download.v1.url_classification',
        'download.v2.first_level_thread',
        'download.v3.proxy_judgment',
        'download.v4.proxy_size_retrieval',
        'download.v4.regular_size_retrieval',
        'download.v5.thread_determination',
        'download.v6.conclusion.conclusion',
        'download.v6.DynamicOptimization.thread_optimizer',
        'download.v6.install.Secondary_thread_install',
        'download.v6.install.Secondary_thread_request',
        'download.v6.merge.merge',
        'download.v6.progress.progress',
        'download.v6.progress.progressbar.ProgressBar',
        'download.v6.Secondary_thread.DownloadConfig',
        # 添加 Playwright 相关依赖
        'playwright',
        'playwright.sync_api',
        'playwright._impl._api_types',
        'playwright._impl._browser',
        'playwright._impl._browser_context',
        'playwright._impl._connection',
        'playwright._impl._event_context_manager',
        'playwright._impl._generated',
        'playwright._impl._helper',
        'playwright._impl._impl_to_api_mapping',
        'playwright._impl._loop_handler',
        'playwright._impl._page',
        'playwright._impl._path_utils',
        'playwright._impl._sync_base',
        'playwright._impl._transport',
        'playwright._impl._type_help',
        'playwright._impl._validator',
        'playwright._impl._wait_helper',
        'playwright._impl.asset',
        'playwright._impl.async_base',
        'playwright._impl.browser_type',
        'playwright._impl.cdp_session',
        'playwright._impl.download',
        'playwright._impl.element_handle',
        'playwright._impl.error',
        'playwright._impl.frame',
        'playwright._impl.js_handle',
        'playwright._impl.network',
        'playwright._impl.playwright',
        'playwright._impl.selectors',
        'playwright._impl.stream',
        'playwright._impl.sync_base',
        'playwright._impl.transport',
        'playwright._impl.websocket',
        'pyee.base',
        'pyee.asyncio',
        'sqlite3',
        'sqlite3.dbapi2',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Hoxino',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 设置为False以隐藏控制台窗口
    disable_windowed_traceback=False,
    target_arch=None,
)
=======
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['Hoxino.py'],  # 只保留主入口文件
    pathex=[],
    binaries=[],
    datas=[
        ('resources', 'resources'),  # 包含资源文件
    ],
    hiddenimports=[
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'queuemanagement',
        'queuemanagement.queuemanagement',
        'ui',
        'ui.Main_ui',
        'ui.setting_ui',
        'ui.tabmanager.tab_manager',
        'ui.PerformanceEvaluation.performance_evaluator',
        'ui.Miscellaneous.Backstage',
        'ui.menu.menu',
        'ui.menu.menu1',
        'ui.list.list',
        'Communications.url_receiver',
        'download.Pausemonitoring.Pause_monitoring',
        'download.util.Settings_util',
        'download.v1.url_classification',
        'download.v2.first_level_thread',
        'download.v3.proxy_judgment',
        'download.v4.proxy_size_retrieval',
        'download.v4.regular_size_retrieval',
        'download.v5.thread_determination',
        'download.v6.conclusion.conclusion',
        'download.v6.DynamicOptimization.thread_optimizer',
        'download.v6.install.Secondary_thread_install',
        'download.v6.install.Secondary_thread_request',
        'download.v6.merge.merge',
        'download.v6.progress.progress',
        'download.v6.progress.progressbar.ProgressBar',
        'download.v6.Secondary_thread.DownloadConfig',
        # 添加 Playwright 相关依赖
        'playwright',
        'playwright.sync_api',
        'playwright._impl._api_types',
        'playwright._impl._browser',
        'playwright._impl._browser_context',
        'playwright._impl._connection',
        'playwright._impl._event_context_manager',
        'playwright._impl._generated',
        'playwright._impl._helper',
        'playwright._impl._impl_to_api_mapping',
        'playwright._impl._loop_handler',
        'playwright._impl._page',
        'playwright._impl._path_utils',
        'playwright._impl._sync_base',
        'playwright._impl._transport',
        'playwright._impl._type_help',
        'playwright._impl._validator',
        'playwright._impl._wait_helper',
        'playwright._impl.asset',
        'playwright._impl.async_base',
        'playwright._impl.browser_type',
        'playwright._impl.cdp_session',
        'playwright._impl.download',
        'playwright._impl.element_handle',
        'playwright._impl.error',
        'playwright._impl.frame',
        'playwright._impl.js_handle',
        'playwright._impl.network',
        'playwright._impl.playwright',
        'playwright._impl.selectors',
        'playwright._impl.stream',
        'playwright._impl.sync_base',
        'playwright._impl.transport',
        'playwright._impl.websocket',
        'pyee.base',
        'pyee.asyncio'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Hoxino',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 设置为False以隐藏控制台窗口
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,    entitlements_file=None,
    icon='resources/icons/app_icon.png'  # 应用程序图T
)
>>>>>>> 2d5d9d9cf12d707f2c5354c07328162bc648e520
